[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "test-contract"

[proxy]
enabled = true
address = "0x40d4dd56a9f06c50eb0b622eacc7e1b32ccc34a40407075d1c1b4be2094f931b"

[dependencies]
